name: automatic-audiolatents
channels:
  - pytorch
  - nvidia
  - xformers/label/dev
dependencies:
  - python=3.9
  - pip
  - pytorch
  - pytorch-cuda
  - torchvision
  - ffmpeg
  - xformers
  - llvmlite
  - numpy
  - protobuf
  - grpcio
  - imageio
  - sentencepiece
  - tensorflow
  - tensorboard
  - absl-py
  - accelerate
  - addict
  - aiohttp
  - aiosignal
  - albumentations
  - anyio
  - astunparse
  - async-timeout
  - blas
  - diffusers
  - einops
  - fairscale
  - fastapi
  - ffmpeg
  - flatbuffers
  - ftfy
  - gast
  - gdown
  - pip:
    - bitsandbytes
    - gfpgan
    - librosa
    - open-clip-torch
    - srt
    - git+https://github.com/openai/CLIP.git@main#egg=clip
